### ISSUE TITLE
Don't know how to build task 'lamby:install'

### ISSUE THREAD

**Issue by hopewise** [customink/lamby#116]
Hello

I have created a new rails app, and added the lamby gem, however, running `./bin/rake -r lamby lamby:install` results into:

```
rake aborted!
Don't know how to build task 'lamby:install' (See the list of available tasks with `rake --tasks`)
```

even if use `bundle exec`, I get the same issue, is there anything I am missing?

or, do I have totally depend on lamby-cookiecutter template?

**Comment by metaskills** [comment]
A few thoughts. 1) Getting the install working. If you are doing a require false in your Gemfile like the guides say, then you need to do the require when running the task. For example `./bin/rails -rlamby ...` or `./bin/rake -rlamby ...` 2) The install methods are not really useful. They are not maintained and feature rich as what we do in the cookie cutter when making a new application. Please consider reviewing what these two files accomplish instead.

- https://github.com/customink/lamby-cookiecutter-ci/blob/master/bin/_lambify
- https://github.com/customink/lamby-cookiecutter-ci/blob/master/bin/_inserts

**Comment by hopewise** [comment]
Thanks @metaskills , I am reading the docs, but I am still not sure how to change this at the `_deploy`

```
IMAGE_REPOSITORY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/my-awesome-lambda"
```

how was `my-awesome-lambda` got populated into the line? and how to customize it?

also, how would I create the API resource at AWS API integration that would get mapped to my rails app resource at routes?

**Comment by metaskills** [comment]
>  but I am still not sure how to change this at the _deploy

You only need to change `my-awesome-lambda` to your application's name. The script will work when either run locally or better yet, via a CI/CD system like GitHub. https://lamby.custominktech.com/docs/quick_start#deploy-with-github-actions

> how would I create the API resource at AWS API integration that would get mapped to my rails app resource at routes?

That does not happen. API Gateway is a simple proxy. Think of it as NGINX but managed. Your Rails application has no knowledge of API Gateway.

**Comment by metaskills** [comment]
> then, I just have to create the proper API endpoint at the AWS API Gateway that was created by AWS Sam?

No, you only have to deploy the SAM template (https://github.com/customink/lamby-cookiecutter-ci/blob/master/lambify/template.yaml#L30-L59) which creates a Lambda Function with your Rails app in it and then API Gateway proxies all requests to it.

> Can you please point me where its defined? I checked template.yaml but has no application name.

Sure, again, please look at the two links I shared above. Please do not use the lamby:install, but those. You will see things like `{% include "_cctmp/dash_name.txt" %}` vs `my-awesome-lambda`. So you would replace the cookie cutter cctmp template stuff with your apps name. Does that make sense?

**Comment by hopewise** [comment]
Thanks @metaskills , but the link you shared is broken, can you fix it please.

**Comment by metaskills** [comment]
My bad, fixed them all above. In both comments.

**Comment by hopewise** [comment]
Thanks @metaskills , I have tried on a new rails app, and it worked so well!

However, I am still not sure how to apply it for a pre existing rails app. I've checked here https://lamby.custominktech.com/docs/anatomy , but isn't there a command line to lambify the existing project?  I would say a rake task to lambify the project would be a great thing to have.

Shall I just copy core lamby files including bin scripts into the rails project, and then simply run:

```
$ ./bin/bootstrap
$ ./bin/setup
$ ./bin/deploy
```

? notice that setup and deploy files are not in the [lamby-cookiecutter](https://github.com/customink/lamby-cookiecutter) repo.

Thanks again!

**Comment by hopewise** [comment]
@metaskills ?

**Comment by palya** [comment]
I was able to solve this issue by removing `require: false` from `gem "lamby", require: false`.

**Comment by metaskills** [comment]
I recently refactored the Lamby Cookiecutter to follow this pattern and outlined all the changes. It actually simplifies a lot. Review here:

* https://github.com/customink/lamby-cookiecutter/pull/21
* https://github.com/customink/lamby-cookiecutter/commit/4945ed2ef3ccc276763aa43c32714bc4bb9251bc

You will see that require false is no longer needed in Lamby v4 too. New guides will be up in a few weeks.
