### ISSUE TITLE
uninitialized constant Lamby::Rack::Utils (NameError)

### ISSUE THREAD

**Issue by jonathantribouharet** [customink/lamby#123]
Hi,
I'm trying to use Lamby for a ruby app (not Rails, just pure ruby) and there is a small error here: 
https://github.com/customink/lamby/blob/e56f6312386ded4b8f311b6e90f983f8de68815c/lib/lamby/rack.rb#L99

it should be `::Rack::Utils`.

**Comment by metaskills** [comment]
Indeed! Fixing that now.

**Comment by metaskills** [comment]
Just pushed v3.1.3. Should be available soon, can you let me know if that works?

**Comment by jonathantribouharet** [comment]
It's working, perfect!
