### ISSUE TITLE
An error occurred (ValidationError) when calling the CreateChangeSet operatio

### ISSUE THREAD

**Issue by richardsondx** [customink/lamby#132]
I keep getting this error with no verbose and it is not really clear what's happening.

```
Error: Failed to create changeset for the stack: {name}-production, An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-east-1:{url} is in ROLLBACK_COMPLETE state and can not be updated.
```
1. Where can I find a list of all the required Permission / Policy for IAM? It is not in the guide.
2. Any idea what may be causing the issue above? 

All the solutions I found on stack-overflow didn't work:
1. One solution was saying to add "CAPABILITY_IAM but it's already set.\
2. Another recommend to run `aws cloudformation delete-stack --stack-name {name}-production --region us-east-1` doesn't work because the stack doesn't even get created. There are no stack on my cloudformation that were created during the deploy.

**Comment by metaskills** [comment]
Might have an error from a previous deploy. Delete the stack and try again is what I have found helps. Can you share if that or something else worked?
