### ISSUE TITLE
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2 for M1

### ISSUE THREAD

**Issue by marcelmatsuokaa** [customink/lamby#144]
Hi
I'm having the error on the deploy step on the quick-start guide:
```
== SAM deploy ==
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```
I've tried multiple approaches that I found, including one of the closed issues here, but I still have some issues.
My Operating System is Mac OS X 12.5.1 with Apple M1 Pro chip.
The only solution that solves the gemu-x86_64 problem was reinstalling sam (while inside the container) with ARM's version of it.
This fix does deploy, but with an internal server error:
```
/usr/local/lib/ruby/3.1.0/bundler/definition.rb:507:in `materialize': Could not find mysql2-0.5.4, debug-1.7.1, bindex-0.8.1, nokogiri-1.14.0-x86_64-linux, nio4r-2.5.8, websocket-driver-0.7.5, io-console-0.6.0, racc-1.6.2, date-3.3.3 in locally installed gems (Bundler::GemNotFound) | /usr/local/lib/ruby/3.1.0/bundler/definition.rb:507:in `materialize': Could not find mysql2-0.5.4, debug-1.7.1, bindex-0.8.1, nokogiri-1.14.0-x86_64-linux, nio4r-2.5.8, websocket-driver-0.7.5, io-console-0.6.0, racc-1.6.2, date-3.3.3 in locally installed gems (Bundler::GemNotFound)
```
I feel that I shouldn't have touched sam or something... I read that you have tested on M1, so I might be doing something wrong, do you have any idea for this case?

**Comment by metaskills** [comment]
Thanks, I'm gonna sort this out. Working on a few issues that relate:

* https://github.com/customink/crypteia/issues/5
* https://github.com/customink/lamby/issues/143

**Comment by metaskills** [comment]
I'm working on this under these issues. https://github.com/customink/lamby/issues/143 Will post back when finished. Getting close.

**Comment by APysnack** [comment]
I'm also hoping for a resolution for this

**Comment by metaskills** [comment]
Getting really really close.

**Comment by metaskills** [comment]
Wrapped up a bunch of work summed up here in the guides. Update to the site should happen shortly. Let me know if this helps. https://github.com/customink/lamby-site/pull/60
