### ISSUE TITLE
Error message: 'github' is undefined

### ISSUE THREAD

**Issue by es-ki** [customink/lamby#184]
I executed the following command listed in the Quick Start guide:
```terminal
docker run \
  --rm \
  --interactive \
  --volume "${PWD}:/var/task" \
  ghcr.io/rails-lambda/lamby-cookiecutter \
  "gh:rails-lambda/lamby-cookiecutter"
```
As a result, the following error was displayed:
```
project_name [my_awesome_lambda]: foo
Unable to create file '.github/workflows/ci.yml'
Error message: 'github' is undefined
Context: {
    "cookiecutter": {
        "_output_dir": "/var/task",
        "_template": "gh:rails-lambda/lamby-cookiecutter",
        "project_name": "foo"
    }
}
```
![a](https://github.com/user-attachments/assets/5e6b22c2-31de-47d8-9aa3-90c069a00d24)

I'm using Windows 11.

**Comment by jeremiahlukus** [comment]
Usually things are ment to work on Linux or Mac. This code works on both of those. 

Are you able to clone and push to other repos? I haven’t used windows in over 10 years so I won’t be able to help you debug this unfortunately. 

I can guarantee that it works on both Linux and Mac however.

**Comment by zvkemp** [comment]
I have the same issue on MacOS 13.4.

**Comment by jeremiahlukus** [comment]
Can you update to a more recent version of Mac and try?  And do you have the latest version of docker running?

Also this command is just pulling a docker image nothing to do with the functionality of Lamby. This  issue should probably be in the cookie cutter repo but you can really expect to have the command to pull g the cookie cutter repo for every version of Mac and Linux.

**Comment by jeremiahlukus** [comment]
For sanity’s sake I’ll pull the repo again when I get home in a couple hours just to make sure nothing has changed since last time I pulled the repo down ( a month or so ago).


For what it’s worth, in my personal applications I create a new application using the rails cli then convert to use lamby or use jumpstart template and convert that

**Comment by jeremiahlukus** [comment]
Sorry @es-ki  and  @zvkemp  seems like this is an issue no idea why/when this happened. Ill work on fixing it.

**Comment by jeremiahlukus** [comment]
https://github.com/rails-lambda/lamby-cookiecutter/issues/48

**Comment by jeremiahlukus** [comment]
Its fixed now you should be able to run the command again

**Comment by es-ki** [comment]
@jeremiahlukus 
Thank you!
It worked!
