### ISSUE TITLE
Application Load Balancer (ALB) Support

### ISSUE THREAD

**Issue by metaskills** [customink/lamby#34]
For a few months now Lambda supports execution via an ALB vs ApiGateway which is overkill for a simple HTTP/HTTPS proxy. I recently saw this tweet which stated the same.

https://twitter.com/alexbdebrie/status/1131921493875712000

However, this feature request in SAM has been open for awhile.

* https://github.com/awslabs/aws-sam-cli/issues/1008
* https://github.com/awslabs/serverless-application-model/issues/721

What interests me most is learning what the event & context look like when using an ALB and how/if Lamby is needed. 

## Resources

* [Using AWS Lambda with an Application Load Balancer](https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html)
* [ALB-Lambda-Target-HelloWorld](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:072567720793:applications~ALB-Lambda-Target-HelloWorld)=
* [User Contributed SAM Template.yml Example](https://github.com/s0enke/cloudformation-templates/blob/master/templates/lambda-alb-sam-sample.yaml)
* [Same But With Auth0](https://www.peterhanssens.com.au/blog/2019-05/alb-to-lambda-with-auth0-authentication/)
* [Tutorial: Create an Application Load Balancer Using the AWS CLI](https://github.com/awsdocs/elb-application-load-balancers-user-guide/blob/master/doc_source/tutorial-application-load-balancer-cli.md)
* [ALB-Lambda-Target-HelloWorld](https://github.com/aws/elastic-load-balancing-tools/tree/master/application-load-balancer-serverless-app/helloworld)

**Comment by lvh** [comment]
How is this distinct from #7?

**Comment by metaskills** [comment]
Whoops, good call out. Closed that other one.
