### ISSUE TITLE
Integration with non rails

### ISSUE THREAD

**Issue by pchaganti** [customink/lamby#60]
Can Lamby be integrated with other non rails apps such as Sinatra? 

thanks!

**Comment by metaskills** [comment]
Correct! It has always been about a basic Rack interface which means anything Rack, including Sinatra. There was some work in June where we removed some specific Rails deps. See #56 for the work and please let me know if you have any issues using it with Sinatra. 

Oh, reminder, it has to be rack v2 or higher. The means Rails v5.2 or up but I do not know what that may mean for Sinatra. Thanks!!!
