### ISSUE TITLE
Support Multi-Value Headers for ALB

### ISSUE THREAD

**Issue by atwoodjw** [customink/lamby#64]
Using the cookie-cutter `app.rb` w/ the ALB rack middleware, I'm seeing malformed responses. Looks like Lamby doesn't handle responses with multi-value headers. Works for me if I add the following, but I think it probably makes sense to fix the underlying issue.

```
def handler(event:, context:)
  result = Lamby.handler $app, event, context, rack: :alb

  # Lamby doesn't handle responses with multi-value headers.
  result[:multiValueHeaders]['Set-Cookie'] = result[:multiValueHeaders]['Set-Cookie'][0].split("\n")
  result.delete(:headers)

  result
end
```

**Comment by metaskills** [comment]
Interesting, can you propose a fix to this file? https://github.com/customink/lamby/blob/master/lib/lamby/rack_alb.rb For example, is this [`multi_value?`](https://github.com/customink/lamby/blob/master/lib/lamby/rack_alb.rb#L8) not returing true or false correctly? Or is it that we should add a line after here (https://github.com/customink/lamby/blob/master/lib/lamby/rack_alb.rb#L14) that does what you are proposing?

**Comment by metaskills** [comment]
Thinking https://github.com/customink/lamby/pull/75 fixes this and if not please re-open.
