### ISSUE TITLE
[TODO] Application Load Balancer Support

### ISSUE THREAD

**Issue by metaskills** [customink/lamby#7]
**AWS Lambda functions as targets for Application Load Balancers** - [AWS Docs](https://aws.amazon.com/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/)

As of yet this is not part of the SAM spec (https://github.com/awslabs/aws-sam-cli/issues/1008) however it is possible if you decide to manually set things up. At some later time I will update this issue to explore and describe that manual process if others are interested.

**Comment by danil-smirnov** [comment]
I'm very interested! Please provide the info

**Comment by metaskills** [comment]
Sure, won't be able to get to this for a week or so at least. But would you mind sharing a little why this is needed for you or how an ALB would be used? For example, so far I've done a few learning experiments where I deployed a Rails app to both us-east-1 and us-west-2 and then used Route53's latency based routing described in #10 and it worked really well. If your app is architected like that. What type of arch would yours be to use an ALB? I'm still new to their use cases and how one might be used with CloudFront, Route53, etc. Thanks in advance!

**Comment by metaskills** [comment]
Closing in favor of #34
