### ISSUE TITLE
Updateing ReadMe with Getting Started section

### ISSUE THREAD

**Issue by mtrolle** [customink/lamby#70]
Hi,

I really think the `ReadMe.md` deserves a Getting Started section. The cookiecutter documentation currently linked is a good place to get started of course, but it also makes a number of assumptions. 

I would be happy to take a stab at writing a few lines for this including:
- [ ] What AWS services are used and why
- [ ] Setting up AWS cli
- [ ] What AIM permissions are required to deploy your first function 
- [ ] Running generators
- [ ] What files you might wanna go through yourself after having run the generator (e.g. `template.yaml` and `bin/deploy` to change function names etc.)
- [ ] Info about working in readonly filesystem (disabling e.g. `bootsnap` gem in Rails 6+, sessions etc)
- [ ] What if you wanna use asset pipeline (uncommenting nodejs in `Dockerfile-build` and `bin/_build` precompiling)
- [ ] Serving base64 (images etc) https://github.com/customink/lamby-cookiecutter/blob/master/inserts/config/environments/production.rb#L7-L10
- [ ] etc.

**Comment by metaskills** [comment]
Agreed, but what about the duplication with the product site and online guides at this site https://lamby.custominktech.com ? Should we put everything there and try to drive traffic over?

**Comment by mtrolle** [comment]
Coming from the outside my experience is that the website is heavily focused on the cookiecutter.
It's a great reference point and everybody should start there, but I would suggest the ReadMe file focus more on the core Lamby gem and how you get this up and running in existing environments.

You have made a lot of decisions in the cookiecutter project that isn't clearly documented. E.g. I'm just right now trying to spin up a fresh Rails install with Lamby and are now experiencing that I need to remove the default included `bootsnap` gem. Documenting such things in the ReadMe directly would be beneficial for newcomers I think.

So it's not my goal to duplicate the knowledge already present on the website. Only supplementing it.

**Comment by metaskills** [comment]
Agreed, we need it. But I do like the idea of this README pointing to the Lamby site. We could easily add a new page for upgrade concerns. Existing Rails apps have a huge surface area of what might not work. I never made a decision on Bootsnap based on evidence. This line here (https://github.com/customink/lamby-cookiecutter/blob/master/bin/_rails-new#L25) was simply because I knew I never needed it for the starter.

So yes, we need more guides, but I would really like to see a new "Upgrade" section on the site.

**Comment by metaskills** [comment]
Going a) always push people to the Lamby site in the README and b) work on an upgrade section for the Lamby guides.
