### ISSUE TITLE
quickstart doenst start 

### ISSUE THREAD

**Issue by JGamboa** [customink/lamby#77]
Im getting the next log 

Successfully built 9ace8a356c94b5b4581b63de7ae42807592f214de87e6f89a281c4479d292e2f
WARNING: The SSH_AUTH_SOCK variable is not set. Defaulting to a blank string.
Creating my_awesome_lambda_my-awesome-lambda_run ... error

ERROR: for my_awesome_lambda_my-awesome-lambda_run  Cannot create container for service my-awesome-lambda: invalid volume specification: '.:.:rw': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute

ERROR: for my-awesome-lambda  Cannot create container for service my-awesome-lambda: invalid volume specification: '.:.:rw': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute
ERROR: Encountered errors while bringing up the project.

I used the quickstart guide, but it didnt event start.-

**Comment by metaskills** [comment]
I've seen this recently too. Did you get it sorted out? I had some solutions on my side but wanted to match them up with yours.

**Comment by metaskills** [comment]
Are you on Linux?

**Comment by JGamboa** [comment]
Yes, im using linux, i have the solution but im not sure if is the solution or not, i will try on another clean environment and ill try.

i think that its need the ssh server started.

**Comment by metaskills** [comment]
Interesting, I saw this error on GitHub Actions recently. I found when doing `COMPOSE_FILE=docker-compose.yml ...` where `...` is whatever bin script you were running that used `docker-compose` would help but that did not make sense to me right away since there is only one compose file, no composites.

**Comment by JGamboa** [comment]
i will try tomorrow, today i cant >:D , but i have two thinks that i think that can work, one is the ssh server but i really think it isnt, the principal problem is that doenst find connection with the ssh-agent

**Comment by JGamboa** [comment]
if im not wrong this make it work

 eval `ssh-agent`

**Comment by JGamboa** [comment]
![imagen](https://user-images.githubusercontent.com/4482664/111377278-369a9100-867f-11eb-9872-3965c9a4b0a5.png)

**Comment by metaskills** [comment]
Updated the starter (https://github.com/customink/lamby-cookiecutter/pull/10) which has changes that make working with Linux a little easier. The starter now also removes the SSH stuff and the guides (https://lamby.custominktech.com/docs/bin_scripts_build_and_deploy#using-private-gems-on-github) link to that article. If there is anything you think we should add to the guides or the article, please let me know. Was not able to reproduce your issue locally so I need a bit of help there. Likewise if the current methods work for you, let me know. Thanks!
