### ISSUE TITLE
Synchronous Migrations possible?

### ISSUE THREAD

**Issue by nitsujri** [customink/lamby#86]
Looking to discuss this topic as I haven't found a solution that I'm 100% sold on.

Migrations are discussed in the [starting docs](https://github.com/customink/lamby/pull/80) and [here as directly callable](https://github.com/customink/lamby/pull/80).

For me, ideally I'd like to keep the migrations as part of the deployment process, synchronous specifically. Async migrations require the code to be pretty robust with regards to referencing new columns and multiple deployments to get to the finalized state.

Fargate is a path I currently use for another production product:

  - Allows migration to run longer than 15 minutes (crazy but I've done them before).
  - `aws ecs run-task` allows single execution
  - Can be synchronous via polling through `aws ecs describe-tasks`

Lambda could do similar if migrations are limited to 15 minutes.
  - Deploy code to a special migration Lambda function 
  - `curl` to a special/locked-down endpoint/url and wait for response to return.

To make it synchronous, the a separate template/stack would have to hold the migration lambda function.

Thoughts?

**Comment by metaskills** [comment]
I think there are a few approaches too. Here is what I have been thinking, in order.

## Restore #80 Work

But lock it down to a set of constant command strings to be allowed. Allow end user config to define those rules for their stack. In doing so, the default lambda timeout which is set to API Gateway's 30s has to come into play. The options there would vary depending on where you want your runner functions. A) If web function, Increase the web function's timeout as needed. Max would be 15m. In theory, API Gateway will still timeout at 30s but a function could be "spinning" which means it would not get re-used by web requests (positive) and would certainly increase concurrency needs. Does not seem like a big deal. B) Create a tasks function (like Lambdakiq outlines with jobs) in the same stack and have that be a simple task runner with 15m timeout.

## Pseudo Lambda SSH Console Access

Open source some work I am doing with Terraform to spin up a Cloud9 based AMI EC2 jumphost in the same VPC as Lambda that would have permissions and tools to pull down ECR images in your account. This would work give you a console for as long as whatever the timeout is for the Cloud9 instance to spin back down. Default 30m, but could be longer. Opens up any task and gives Rails users the power to console in and explore/debug. Should work if you add the DB credentials via Dotenv to the secure image. The only negative I can think of is that this console instance could not mirror IAM permissions of the Runtime role. For example, say you are using DynamoDB, S3, App Config Creds, or even Aurora with rotated IAM creds, anything that the Runtime roles uses... then unless I bake in some behavior with this EC2 jumphost (via simple SDK scripting and IAM capabilities to assume other roles) the jumphost would break for muse use cases. FYI, I do think it would be straightforward to allow the jumphost to query a stack and re-use a Runtime role.

## Other

Thoughts?

**Comment by nitsujri** [comment]
> Restore #80 Work

I think this is the better direction. It allows us to decide how we want to run the migration wether manually or async or sync. 

I've started going down the direction of "sync" firing a direct lambda invoke (cold-start first hit; looks like event bridge) as part of the CI/CD process (currently using CodeBuild) by running:

``` bash
        #!/bin/bash
        FUNCTION_NAMES=('WebRailsLambda' 'ApiRailsLambda')
        for func_name in ${FUNCTION_NAMES[@]}; do
          aws lambda invoke \
            --function-name $(aws lambda list-functions --query "Functions[].FunctionName | [?contains(@, '$func_name')] | [0]" --output text) \
            --cli-binary-format raw-in-base64-out \
            --payload "{\"source\": \"manual-invoke\", \"detail\": \"KeepWarm\", \"detail-type\": \"func_name: ${func_name}\", \"resources\": [\"KeepWarm\", \"FirstHit\"]}" \
            out \
            --log-type Tail \
            --query 'LogResult' \
            --output text | base64 -d
        done
```

I can do similar w/ something like #80 work. (technically, I can do execute it directly via `Rails.task`, but I think standardizing on #80 is good)

> Pseudo Lambda SSH Console Access

While SSH/Pseudo SSH is useful, I'm personally looking for more automated migrations. Manual migrations, to me, aren't true CI/CD which I absolutely love. Fire & forget.

But for SSH, I did some work for [Fargate that allows SSH](https://github.com/jenfi-eng/sshd-docker) to run on a separate task. It's not a drop in here (Fargate, Alpine, separate task...), but the concept is the same, allow direct SSH into the Lambda container.

> API Gateway will still timeout at 30s

Oh crap, thanks for this CRITICAL information. I didn't realize and this will dictate a few key processes.

> Open source some work I am doing with Terraform to spin up a Cloud9 based AMI EC2 jumphost in the same VPC as Lambda that would have permissions and tools to pull down ECR images in your account.

To be explicit, a Lambda in a customer controlled VPC doesn't get a public IP which then means it should part of a private VPC + NAT Gateway/Instance otherwise the connection will never complete since it can't communicate outwards.

**Comment by metaskills** [comment]
Cool, I'll have a PR for #80 to come back to life in a few days. Already have most of the work done. What I like about it is that it will give you full control thru an event which is decoupled from any CI/CD system. Want to ClickOps it in the console, fine. Want to push a message to EventBridge, cool. What ever works... and since it is an invoke event... API Gateway is not involved at all.

**Comment by metaskills** [comment]
https://github.com/customink/lamby/pull/93
