### ISSUE TITLE
Cold Start Guides w/Bootsnap

### ISSUE THREAD

**Issue by metaskills** [customink/lamby#88]
I've done several weeks of work to both measure and update/adopt Bootsnap (http://github.com/Shopify/bootsnap) patterns with Lambda. I'd like to add a Cold Start section that speaks to this and other data points for optimizing Rails performance on Lambda.

**Comment by metaskills** [comment]
Remember to mention how the Lamby starter uses `AutoPublishAlias: live` and why this is important for deploy rollouts in high traffic scenarios.

**Comment by metaskills** [comment]
https://lamby.custominktech.com/docs/cold_starts

**Comment by dcunning** [comment]
Your write-up really helped me out this week. Thanks!

(for future viewers) Its URL changed a little bit. It's now at: https://lamby.custominktech.com/docs/cold-starts
