### ISSUE TITLE
More than just HTTP API

### ISSUE THREAD

**Issue by metaskills** [customink/lamby#89]
The starter project assumes a public facing application using HTTP API. But Lamby works fine for REST API & ALBs. Outline why these are important and demo code changes to use. Propose the following guides additions and updates.

- New "Using REST API" section. Warn that this is not an ideal simple public proxy since HTTP API is easier and cheaper. Showcase how to change starter template code to use. Include guides on this page for Custom Domain Names.
- New "Private VPC Applications" section. Calls out two methods. First is the easier ALB Only method with 1MB response limit callout. Note here about how rack-deflater can help. Second method is the fun REST API (link above) with a crazy VPC Endpoint and ALB proxy. AWS just published (finally) guides (https://docs.aws.amazon.com/apigateway/latest/developerguide/private-api-tutorial.html) on this too so we can link to it. Include guides on this page for Custom Domain Names.
- Update "Custom Domain Names" with callouts to each new section above and link to each page. Keep this guide page assuming public HTTP API with callouts.

**Comment by metaskills** [comment]
Remember to fix the docs here in the legacy migration section. https://lamby.custominktech.com/docs/anatomy#installing-for-legacy-applications

**Comment by kornate** [comment]
First off, cloud hero, I adore your frequent commits and seeing lamby skyrocket in maturity so quickly!

I like the idea of the demo including guidance around private applications, as this is precisely what I'm trying to achieve at the moment, breaking up a monolithic rails 5 application as a complete rewrite... being a docker-pro lambda-amateur. If I can help somehow, I will. 

Thank you for your dedication!

**Comment by kornate** [comment]
Do you have any suggestions on how to secure a deployment to local subnets only? Thank you

**Comment by metaskills** [comment]
Yup, I'm going to need to update some sections. Here is what I see.

Create a new VPC guides section. Link to it from the Simple MySQL Database (https://lamby.custominktech.com/docs/database_options#simple-mysql-setup) section. I will also need to pull this sub section of the RDS Proxy (https://lamby.custominktech.com/docs/database_options#3-configure-aws-sam) to point to the new VPC guide page. FYI, assigning your Lambda a VpcConfig is how you can talk to Databases and also make it private. So 

The guides for the private app will be based off this. Hope it helps for now. https://gist.github.com/metaskills/e417111c9525d1c4f1c162cb81d72595

**Comment by metaskills** [comment]
Done, site should update shortly. https://github.com/customink/lamby_site/commit/60df7518023181ebc48e7c5a33ea686bed25cff4
