### ISSUE TITLE
GitLab CI/CD

### ISSUE THREAD

**Issue by kornate** [customink/lamby#95]
GitHub actions are great, but support in the docs/demo for Gitlab CI/CD would be much welcome as an alternative/free/self hosted solution.

https://docs.gitlab.com/ee/user/project/clusters/serverless/aws.html#aws-serverless-application-model

**Comment by metaskills** [comment]
Well, the way we use Docker for development, test, and deploy means the CI/CD is 100% portable since SAM is in the container. Just run `./bin/bootstrap` and `./bin/deploy` with the right credentials in place.

**Comment by metaskills** [comment]
See the latest files in the Lamby Cookiecutter for GitHub Actions. I think they can provide how easy it would be to use GitLab? https://github.com/customink/lamby-cookiecutter/tree/master/lambify/.github/workflows
